<?php
/**
 * CommitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * CommitTest Class Doc Comment
 *
 * @category    Class
 * @description Commit refers to a VCS commit and all associated details.
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommitTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Commit"
     */
    public function testCommit()
    {
    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "authorId"
     */
    public function testPropertyAuthorId()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "authorEmail"
     */
    public function testPropertyAuthorEmail()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "authorIdentity"
     */
    public function testPropertyAuthorIdentity()
    {
    }

    /**
     * Test attribute "repositoryId"
     */
    public function testPropertyRepositoryId()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }
}
