<?php
/**
 * EpicTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * EpicTest Class Doc Comment
 *
 * @category    Class
 * @description An Epic is a collection of stories that together might make up a release, a milestone, or some other large initiative that you are working on.
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EpicTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Epic"
     */
    public function testEpic()
    {
    }

    /**
     * Test attribute "appUrl"
     */
    public function testPropertyAppUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "started"
     */
    public function testPropertyStarted()
    {
    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "mentionIds"
     */
    public function testPropertyMentionIds()
    {
    }

    /**
     * Test attribute "memberMentionIds"
     */
    public function testPropertyMemberMentionIds()
    {
    }

    /**
     * Test attribute "associatedGroups"
     */
    public function testPropertyAssociatedGroups()
    {
    }

    /**
     * Test attribute "projectIds"
     */
    public function testPropertyProjectIds()
    {
    }

    /**
     * Test attribute "storiesWithoutProjects"
     */
    public function testPropertyStoriesWithoutProjects()
    {
    }

    /**
     * Test attribute "completedAtOverride"
     */
    public function testPropertyCompletedAtOverride()
    {
    }

    /**
     * Test attribute "productboardPluginId"
     */
    public function testPropertyProductboardPluginId()
    {
    }

    /**
     * Test attribute "startedAt"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "completedAt"
     */
    public function testPropertyCompletedAt()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "globalId"
     */
    public function testPropertyGlobalId()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "productboardUrl"
     */
    public function testPropertyProductboardUrl()
    {
    }

    /**
     * Test attribute "plannedStartDate"
     */
    public function testPropertyPlannedStartDate()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "milestoneId"
     */
    public function testPropertyMilestoneId()
    {
    }

    /**
     * Test attribute "requestedById"
     */
    public function testPropertyRequestedById()
    {
    }

    /**
     * Test attribute "epicStateId"
     */
    public function testPropertyEpicStateId()
    {
    }

    /**
     * Test attribute "labelIds"
     */
    public function testPropertyLabelIds()
    {
    }

    /**
     * Test attribute "startedAtOverride"
     */
    public function testPropertyStartedAtOverride()
    {
    }

    /**
     * Test attribute "groupId"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "groupMentionIds"
     */
    public function testPropertyGroupMentionIds()
    {
    }

    /**
     * Test attribute "productboardId"
     */
    public function testPropertyProductboardId()
    {
    }

    /**
     * Test attribute "followerIds"
     */
    public function testPropertyFollowerIds()
    {
    }

    /**
     * Test attribute "ownerIds"
     */
    public function testPropertyOwnerIds()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "productboardName"
     */
    public function testPropertyProductboardName()
    {
    }

    /**
     * Test attribute "deadline"
     */
    public function testPropertyDeadline()
    {
    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }
}
