<?php
/**
 * GroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * GroupTest Class Doc Comment
 *
 * @category    Class
 * @description A Group.
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Group"
     */
    public function testGroup()
    {
    }

    /**
     * Test attribute "appUrl"
     */
    public function testPropertyAppUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "numStoriesStarted"
     */
    public function testPropertyNumStoriesStarted()
    {
    }

    /**
     * Test attribute "mentionName"
     */
    public function testPropertyMentionName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "globalId"
     */
    public function testPropertyGlobalId()
    {
    }

    /**
     * Test attribute "colorKey"
     */
    public function testPropertyColorKey()
    {
    }

    /**
     * Test attribute "numStories"
     */
    public function testPropertyNumStories()
    {
    }

    /**
     * Test attribute "numEpicsStarted"
     */
    public function testPropertyNumEpicsStarted()
    {
    }

    /**
     * Test attribute "numStoriesBacklog"
     */
    public function testPropertyNumStoriesBacklog()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "displayIcon"
     */
    public function testPropertyDisplayIcon()
    {
    }

    /**
     * Test attribute "memberIds"
     */
    public function testPropertyMemberIds()
    {
    }

    /**
     * Test attribute "workflowIds"
     */
    public function testPropertyWorkflowIds()
    {
    }
}
