<?php
/**
 * HistoryChangesStoryLinkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * HistoryChangesStoryLinkTest Class Doc Comment
 *
 * @category    Class
 * @description The changes that have occurred as a result of the action.
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoryChangesStoryLinkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HistoryChangesStoryLink"
     */
    public function testHistoryChangesStoryLink()
    {
    }

    /**
     * Test attribute "verb"
     */
    public function testPropertyVerb()
    {
    }

    /**
     * Test attribute "objectId"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "subjectId"
     */
    public function testPropertySubjectId()
    {
    }
}
