<?php
/**
 * IterationSlimTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * IterationSlimTest Class Doc Comment
 *
 * @category    Class
 * @description IterationSlim represents the same resource as an Iteration, but is more light-weight. Use the [Get Iteration](#Get-Iteration) endpoint to fetch the unabridged payload for an Iteration.
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IterationSlimTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IterationSlim"
     */
    public function testIterationSlim()
    {
    }

    /**
     * Test attribute "appUrl"
     */
    public function testPropertyAppUrl()
    {
    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "mentionIds"
     */
    public function testPropertyMentionIds()
    {
    }

    /**
     * Test attribute "memberMentionIds"
     */
    public function testPropertyMemberMentionIds()
    {
    }

    /**
     * Test attribute "associatedGroups"
     */
    public function testPropertyAssociatedGroups()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "globalId"
     */
    public function testPropertyGlobalId()
    {
    }

    /**
     * Test attribute "labelIds"
     */
    public function testPropertyLabelIds()
    {
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "groupMentionIds"
     */
    public function testPropertyGroupMentionIds()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "followerIds"
     */
    public function testPropertyFollowerIds()
    {
    }

    /**
     * Test attribute "groupIds"
     */
    public function testPropertyGroupIds()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }
}
