<?php
/**
 * IterationAssociatedGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * IterationAssociatedGroupTest Class Doc Comment
 *
 * @category    Class
 * @description IterationAssociatedGroup
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IterationAssociatedGroupTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IterationAssociatedGroup"
     */
    public function testIterationAssociatedGroup()
    {
    }

    /**
     * Test attribute "groupId"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "associatedStoriesCount"
     */
    public function testPropertyAssociatedStoriesCount()
    {
    }
}
