<?php
/**
 * LabelStatsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LabelStatsTest Class Doc Comment
 *
 * @category    Class
 * @description A group of calculated values for this Label. This is not included if the slim? flag is set to true for the List Labels endpoint.
 * @package     Timetoreply\Shortcut
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LabelStatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LabelStats"
     */
    public function testLabelStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numRelatedDocuments"
     */
    public function testPropertyNumRelatedDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numEpics"
     */
    public function testPropertyNumEpics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesUnstarted"
     */
    public function testPropertyNumStoriesUnstarted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesTotal"
     */
    public function testPropertyNumStoriesTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numEpicsUnstarted"
     */
    public function testPropertyNumEpicsUnstarted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numEpicsInProgress"
     */
    public function testPropertyNumEpicsInProgress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numPointsUnstarted"
     */
    public function testPropertyNumPointsUnstarted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesUnestimated"
     */
    public function testPropertyNumStoriesUnestimated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numPointsInProgress"
     */
    public function testPropertyNumPointsInProgress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numEpicsTotal"
     */
    public function testPropertyNumEpicsTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesCompleted"
     */
    public function testPropertyNumStoriesCompleted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numPointsCompleted"
     */
    public function testPropertyNumPointsCompleted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesBacklog"
     */
    public function testPropertyNumStoriesBacklog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numPointsTotal"
     */
    public function testPropertyNumPointsTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numStoriesInProgress"
     */
    public function testPropertyNumStoriesInProgress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numPointsBacklog"
     */
    public function testPropertyNumPointsBacklog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numEpicsCompleted"
     */
    public function testPropertyNumEpicsCompleted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
