<?php
/**
 * StoryContentsTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * StoryContentsTaskTest Class Doc Comment
 *
 * @category    Class
 * @description StoryContentsTask
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoryContentsTaskTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StoryContentsTask"
     */
    public function testStoryContentsTask()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "complete"
     */
    public function testPropertyComplete()
    {
    }

    /**
     * Test attribute "ownerIds"
     */
    public function testPropertyOwnerIds()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }
}
