<?php
/**
 * UpdateProjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * UpdateProjectTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateProject
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateProjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateProject"
     */
    public function testUpdateProject()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "daysToThermometer"
     */
    public function testPropertyDaysToThermometer()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "followerIds"
     */
    public function testPropertyFollowerIds()
    {
    }

    /**
     * Test attribute "showThermometer"
     */
    public function testPropertyShowThermometer()
    {
    }

    /**
     * Test attribute "teamId"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "abbreviation"
     */
    public function testPropertyAbbreviation()
    {
    }
}
