<?php
/**
 * V3FilesBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Timetoreply\Shortcut
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shortcut API
 *
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Timetoreply\Shortcut;

use PHPUnit\Framework\TestCase;

/**
 * V3FilesBodyTest Class Doc Comment
 *
 * @category    Class
 * @description V3FilesBody
 * @package     Timetoreply\Shortcut
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V3FilesBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V3FilesBody"
     */
    public function testV3FilesBody()
    {
    }

    /**
     * Test attribute "storyId"
     */
    public function testPropertyStoryId()
    {
    }

    /**
     * Test attribute "file0"
     */
    public function testPropertyFile0()
    {
    }

    /**
     * Test attribute "file1"
     */
    public function testPropertyFile1()
    {
    }

    /**
     * Test attribute "file2"
     */
    public function testPropertyFile2()
    {
    }

    /**
     * Test attribute "file3"
     */
    public function testPropertyFile3()
    {
    }
}
